name: jmillermedia.github.io
sass:
  style: compressed
  sass_dir: _sass
include:
  - .well-known
collections:
  skills:
    order:
      - HTML.md
      - CSS.md
      - JS.md
      - PHP.md
      - VSCode.md
      - SASS.md
      - Git.md
      - vue.md
      - mySQL.md
      - shopify.md
      - figma.md
      - photoshop.md
      - illustrator.md
      - afterEffects.md
      - premiere.md
      - xd.md
      - inDesign.md
      - lightroom.md
      - videoEditing.md
      - graphicDesign.md
      - motionDesign.md
      - photography.md
      - videoStreaming.md
      - audioEngineering.md
      - audioDesign.md
      - audioEditing.md
      - musicComposition.md